In [3]:
from importlib.metadata import requires

import torch
from flatbuffers.number_types import float32_to_uint32
from tensorboard.summary.v1 import scalar

if torch.cuda.is_available():
    print("GPU is available!")
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"Total Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"CUDA Version: {torch.version.cuda}")
else:
    print("GPU is not available, using CPU.")

GPU is available!
GPU Name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Total Memory: 6.44 GB
CUDA Version: 12.6


In [27]:
#https://pytorch.org/docs/stable/tensors.html
#creating tensor
#scalar
scalar=torch.tensor(1)
scalar

tensor(1)

In [31]:
print(scalar.item())
scalar.item()

1


1

In [40]:
vector=torch.tensor([1,3])
vector

tensor([1, 3])

In [27]:
import torch
float_32_tensor=torch.tensor([3.0,4.0,5.0],
                             dtype=torch.float32,
                             device="cpu",
                             requires_grad=False)
print(float_32_tensor.dtype)
float_32_tensor


torch.float32


tensor([3., 4., 5.])

In [28]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)